name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: joaovbrolcarneiro
          outputs: dist/snake.svg

      - name: Commit and push
        run: |
          git config --local user.name "joaovbrolcarneiro"
          git config --local user.email "your-email@example.com"
          git add -A
          git commit -m "Generated snake.svg"
          git push
