name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Update to use Node.js 16
      - uses: actions/checkout@v3 # Update to v3 to use a newer version of Node.js

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Snake
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: joaovbrolcarneiro
          svg_out_path: dist/snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git config --local user.name "joaovbrolcarneiro"
          git config --local user.email "your-email@example.com"
          git add dist/snake.svg
          git commit -m "Generated snake.svg"
          git push

